a = int(input("Enter the first number \n"))
print ("Thank you! Your first number is", a)
b = int(input("Enter the second number \n"))
print ("Thank you! Your second number is", b)

print ("a + b = ", a+b)
print ("a - b = ", a-b)
print ("a * b = ", a*b)
print ("a / b = ", a/b)
print ("a ** b = ", a**b)
print ("a // b = ", a//b)
print ("a % b = ", a%b)