A = int(input("Enter A value: "))
B = int(input("Enter B value: "))

print("A + B = ", A + B)
print("A - B = ", A - B)
print("A * B = ", A * B)
print("A / B = ", A / B)
print("A **B = ", A **B)
print("A //B = ", A //B)
print("A % B = ", A % B)
