user_name = input("What is your name? \n")
print ("Hello,", (user_name))
user_age = input("How old are you? \n")
print ("Your age is", (user_age))
user_adress = input("Where do you live? \n")
print ("You live in", (user_adress))