A = int(input("GIVE ME NUMBER "))
B = int(input("GIVE ME ANOTHER NUMBER "))
print(f"\n")
print(f"{A} + {B} =", A + B) 
print(f"{A} - {B} =", A - B) 
print(f"{A} * {B} =", A * B) 
print(f"{A} / {B} =", A / B) 
print(f"{A} ** {B} =", A ** B) 
print(f"{A} // {B} =", A // B) 
print(f"{A} % {B} =", A % B)
